In [24]:
import pyodbc
import pandas as pd

In [25]:
cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+"TOBIAS-PC" +
                      ';DATABASE='+"mqtt-db"+';UID='+"TOBIAS-PC\TK"+';Trusted_Connection=yes;')

In [26]:
%%time
df = pd.read_sql("SELECT * FROM TableBinary",cnxn)
df_3min = df.loc[120:180, ['created_at','received_at','sensor_data']]
df_3min

Wall time: 28.5 ms

,created_at,received_at,sensor_data
120,2021-10-21 17:00:25.209458,2021-10-21 17:00:25.209458,b'\x00\x00\x0c\xb0$\xf9SO\xab\r\xca\xb1\x9b\xe...
121,2021-10-21 17:00:26.258177,2021-10-21 17:00:26.258177,b'\x00\x00\x12\xb0#\xf9CO\xaf\r\xeb\xb1\x99\xe...
122,2021-10-21 17:00:27.306365,2021-10-21 17:00:27.306365,b'\x00\x00\x10\xb0%\xf9WO\xae\r\xdc\xb1\x9c\xe...
123,2021-10-21 17:00:28.386657,2021-10-21 17:00:28.386657,b'\x00\x00\x03\xb0$\xf9dO\xb0\r\xe3\xb1\x9b\xe...
124,2021-10-21 17:00:29.419436,2021-10-21 17:00:29.419436,b'\x00\x00#\xb0%\xf9YO\xaf\r\xdc\xb1\xa1\xebtL...
...,...,...,...
176,2021-10-21 17:01:24.156913,2021-10-21 17:01:24.156913,b'\x00\x00\x1a\xb0%\xf9hO\xaf\r\xd4\xb1\xa0\xe...
177,2021-10-21 17:01:25.209791,2021-10-21 17:01:25.209791,"b'\x00\x00\n\xb0""\xf9KO\xaa\r\xdf\xb1\x9a\xebv..."
178,2021-10-21 17:01:26.266059,2021-10-21 17:01:26.266059,b'\x00\x00\x16\xb0$\xf9cO\xb0\r\xdb\xb1\xa0\xe...
179,2021-10-21 17:01:27.311566,2021-10-21 17:01:27.311566,"b'\x00\x00&\xb0""\xf9cO\xaa\r\xe2\xb1\x9f\xebtL..."
180,2021-10-21 17:01:28.367542,2021-10-21 17:01:28.367542,b'\x00\x00(\xb0#\xf9OO\xaf\r\xe7\xb1\x9c\xebcL...

In [27]:
%%time
df2 = pd.read_sql("SELECT * FROM TableDataPackage WHERE package_id >= 120 and package_id <= 179",cnxn)
# hier nur obligatorisch die sensordaten im dataframe als list hinterlegt, deutlich langsamer als 1. Methode
df_new = df2.groupby('package_id').agg({'sensor_data':pd.Series.to_list})
df_new

Wall time: 382 ms

                                                  sensor_data
package_id
120         [0, -20447, -1755, 20321, 3502, -19994, -5222,...
121         [0, -20475, -1755, 20328, 3502, -19995, -5215,...
122         [0, -20457, -1756, 20294, 3498, -20011, -5216,...
123         [0, -20478, -1755, 20302, 3499, -20017, -5215,...
124         [0, -20465, -1755, 20314, 3501, -19996, -5214,...
125         [0, -20447, -1757, 20306, 3498, -20000, -5217,...
126         [0, -20451, -1757, 20293, 3502, -20017, -5220,...
127         [0, -20453, -1755, 20313, 3503, -20010, -5223,...
128         [0, -20447, -1756, 20308, 3502, -20015, -5218,...
129         [0, -20442, -1756, 20298, 3498, -19990, -5223,...
130         [0, -20460, -1755, 20300, 3501, -20001, -5221,...
131         [0, -20478, -1756, 20308, 3502, -19997, -5221,...
132         [0, -20459, -1756, 20312, 3501, -20025, -5220,...
133         [0, -20447, -1757, 20305, 3497, -20008, -5221,...
134         [0, -20473, -1758, 20314, 3504, -20004, -5221,...
135         [0, -20467, -1757, 20319, 3498, -20005, -5223,...
136         [0, -20462, -1756, 20320, 3499, -19993, -5215,...
137         [0, -20446, -1756, 20308, 3499, -20011, -5221,...
138         [0, -20469, -1756, 20324, 3502, -20026, -5217,...
139         [0, -20477, -1755, 20291, 3498, -19991, -5219,...
140         [0, -20449, -1755, 20304, 3504, -19990, -5217,...
141         [0, -20445, -1757, 20306, 3499, -20017, -5223,...
142         [0, -20473, -1758, 20314, 3503, -20013, -5220,...
143         [0, -20452, -1755, 20318, 3502, -20015, -5220,...
144         [0, -20474, -1758, 20324, 3503, -19995, -5215,...
145         [0, -20474, -1758, 20301, 3499, -20020, -5218,...
146         [0, -20463, -1757, 20304, 3503, -20011, -5221,...
147         [0, -20452, -1756, 20320, 3504, -20020, -5215,...
148         [0, -20453, -1758, 20289, 3499, -20004, -5217,...
149         [0, -20474, -1758, 20324, 3500, -19999, -5219,...
150         [0, -20464, -1755, 20314, 3501, -20008, -5218,...
151         [0, -20443, -1755, 20317, 3503, -19994, -5216,...
152         [0, -20445, -1757, 20303, 3499, -20025, -5221,...
153         [0, -20447, -1758, 20326, 3502, -20021, -5217,...
154         [0, -20450, -1756, 20290, 3500, -19995, -5222,...
155         [0, -20478, -1757, 20309, 3498, -19994, -5220,...
156         [0, -20446, -1755, 20306, 3502, -20012, -5217,...
157         [0, -20447, -1757, 20302, 3498, -20011, -5221,...
158         [0, -20457, -1755, 20302, 3504, -20017, -5216,...
159         [0, -20451, -1758, 20307, 3500, -19993, -5223,...
160         [0, -20453, -1756, 20297, 3500, -19991, -5218,...
161         [0, -20469, -1757, 20292, 3499, -20001, -5219,...
162         [0, -20472, -1755, 20302, 3497, -20000, -5218,...
163         [0, -20467, -1757, 20325, 3500, -19991, -5214,...
164         [0, -20464, -1756, 20300, 3499, -19996, -5215,...
165         [0, -20477, -1758, 20327, 3503, -19995, -5215,...
166         [0, -20456, -1756, 20293, 3501, -20021, -5222,...
167         [0, -20441, -1758, 20295, 3501, -19989, -5222,...
168         [0, -20453, -1757, 20315, 3499, -19991, -5221,...
169         [0, -20472, -1755, 20308, 3498, -20007, -5220,...
170         [0, -20450, -1757, 20290, 3501, -19993, -5219,...
171         [0, -20474, -1757, 20295, 3502, -20027, -5217,...
172         [0, -20442, -1758, 20326, 3503, -20003, -5216,...
173         [0, -20467, -1757, 20323, 3499, -19991, -5221,...
174         [0, -20444, -1757, 20328, 3501, -20001, -5223,...
175         [0, -20474, -1755, 20308, 3498, -20021, -5218,...
176         [0, -20443, -1756, 20311, 3498, -20009, -5214,...
177         [0, -20449, -1756, 20295, 3499, -20003, -5222,...
178         [0, -20461, -1755, 20314, 3498, -19995, -5214,...
179         [0, -20477, -1757, 20302, 3498, -19993, -5220,...